package report

import (
	"fmt"
	"strings"
)

// RenderReportText builds the text/plain alternative for the fleet report.
// Generated from the MODEL, never scraped from HTML — it must stay legible
// in clients that prefer plaintext, in previews/notification snippets, and
// for screen readers. Plain ASCII layout, ~72-col friendly.
func RenderReportText(m ReportModel) string {
	var b strings.Builder
	rule := strings.Repeat("=", 64)
	thin := strings.Repeat("-", 64)

	fmt.Fprintf(&b, "%s\r\nFIREWALL MONITOR — %s REPORT\r\n%s\r\n", rule, strings.ToUpper(m.Period), rule)
	fmt.Fprintf(&b, "%s (%s)\r\n\r\n", m.Date, m.Timezone)

	fmt.Fprintf(&b, "%s\r\n", strings.ToUpper(m.StatusHeadline))
	if m.StatusDetail != "" {
		fmt.Fprintf(&b, "%s\r\n", m.StatusDetail)
	}
	b.WriteString("\r\n")

	fmt.Fprintf(&b, "Devices online:   %d / %d\r\n", m.OnlineDevices, m.TotalDevices)
	fmt.Fprintf(&b, "Fleet uptime:     %.1f%%\r\n", m.FleetUptimePct)
	fmt.Fprintf(&b, "Alerts:           %d (%d critical)\r\n", m.TotalAlerts, m.CriticalAlerts)
	if m.PeakThroughput != "" {
		fmt.Fprintf(&b, "Peak throughput:  %s\r\n", m.PeakThroughput)
	}
	if m.TotalTransfer != "" {
		fmt.Fprintf(&b, "Total transfer:   %s\r\n", m.TotalTransfer)
	}

	if len(m.TopTalkers) > 0 {
		fmt.Fprintf(&b, "\r\nTOP TALKERS\r\n%s\r\n", thin)
		for _, t := range m.TopTalkers {
			fmt.Fprintf(&b, "  %-20s %-14s %10s (peak %s)\r\n", t.DeviceName, t.IfaceName, t.TotalHuman, t.PeakHuman)
		}
	}

	if m.SpikeTotal > 0 {
		fmt.Fprintf(&b, "\r\nTRAFFIC SPIKES: %d events (%d critical) on %d interfaces\r\n%s\r\n",
			m.SpikeTotal, m.SpikeCritical, m.SpikeIfaceCount, thin)
		for _, g := range m.SpikeGroups {
			fmt.Fprintf(&b, "  %-20s %-14s x%-3d peak %s  [%s]\r\n", g.DeviceName, g.Interface, g.Count, g.PeakHuman, g.WorstSev)
		}
		if m.SpikeMore > 0 {
			fmt.Fprintf(&b, "  ... and %d more interface(s)\r\n", m.SpikeMore)
		}
	}

	if m.Ops != nil {
		fmt.Fprintf(&b, "\r\nOPERATIONS (LAST %d DAYS)\r\n%s\r\n", m.Ops.Days, thin)
		fmt.Fprintf(&b, "  MTTA %.0f min (%d acked)   MTTR %.0f min (%d resolved)\r\n",
			m.Ops.MTTAMinutes, m.Ops.AckedCount, m.Ops.MTTRMinutes, m.Ops.ResolvedCount)
		for _, n := range m.Ops.Noise {
			fmt.Fprintf(&b, "  %-28s %-20s x%d (%d suppressed)\r\n", n.AlertType, n.DeviceName, n.Count, n.Suppressed)
		}
	}

	if len(m.Devices) > 0 || len(m.MoreDevices) > 0 {
		fmt.Fprintf(&b, "\r\nDEVICES\r\n%s\r\n", thin)
		for _, d := range append(append([]DeviceCard(nil), m.Devices...), m.MoreDevices...) {
			status := "OFFLINE"
			if d.Online {
				status = "online"
			}
			fmt.Fprintf(&b, "  %-20s %-15s %-7s cpu %3.0f%% max  mem %3.0f%% max  up %5.1f%%  alerts %d\r\n",
				d.Name, d.IPAddress, status, d.CPUMax, d.MemMax, d.UptimePct, d.AlertCount)
		}
	}

	fmt.Fprintf(&b, "\r\n%s\r\nGenerated %s by Firewall Monitor", thin, m.GeneratedAt)
	if m.Version != "" {
		fmt.Fprintf(&b, " v%s", m.Version)
	}
	b.WriteString("\r\n")
	return b.String()
}

// RenderCriticalAlertText is the text/plain alternative for the critical
// alert email (mirrors CriticalAlertData).
func RenderCriticalAlertText(d CriticalAlertData) string {
	var b strings.Builder
	rule := strings.Repeat("=", 64)
	fmt.Fprintf(&b, "%s\r\nCRITICAL ALERT: %s\r\n%s\r\n\r\n", rule, d.AlertType, rule)
	fmt.Fprintf(&b, "Time:     %s\r\n", d.Timestamp)
	fmt.Fprintf(&b, "Device:   %s (%s)\r\n", d.DeviceName, d.DeviceIP)
	fmt.Fprintf(&b, "Message:  %s\r\n", d.Message)
	if d.MetricName != "" {
		fmt.Fprintf(&b, "Metric:   %s: %.2f (threshold %.2f)\r\n", d.MetricName, d.CurrentValue, d.Threshold)
	}
	fmt.Fprintf(&b, "Status:   %s\r\n", d.DeviceStatus)
	fmt.Fprintf(&b, "\r\nGenerated by Firewall Monitor\r\n")
	return b.String()
}
