package report

import "html/template"

// criticalAlertTemplate is the HTML template for critical alert emails.
var criticalAlertTemplate = template.Must(template.New("critical").Parse(`<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background:#f4f4f4;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;">

<!-- Header -->
<tr><td style="background:#ea4335;padding:20px 30px;">
  <h1 style="margin:0;color:#ffffff;font-size:22px;">⚠ Critical Alert</h1>
  <p style="margin:5px 0 0;color:#f8c4c0;font-size:13px;">{{.Timestamp}}</p>
</td></tr>

<!-- Alert Details -->
<tr><td style="padding:20px 30px;">
  <table width="100%" cellpadding="8" cellspacing="0" style="border:1px solid #e0e0e0;border-radius:4px;font-size:13px;">
  <tr style="background:#fce8e6;">
    <td style="border-bottom:1px solid #e0e0e0;width:120px;"><strong>Alert Type</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.AlertType}}</td>
  </tr>
  <tr>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Device</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.DeviceName}} ({{.DeviceIP}})</td>
  </tr>
  <tr>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Message</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.Message}}</td>
  </tr>
  {{if .MetricName}}
  <tr>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Metric</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.MetricName}}: {{printf "%.2f" .CurrentValue}} (threshold: {{printf "%.2f" .Threshold}})</td>
  </tr>
  {{end}}
  <tr>
    <td><strong>Status</strong></td>
    <td>{{.DeviceStatus}}</td>
  </tr>
  </table>
</td></tr>

<!-- CPU/Mem Chart if available -->
{{if .CPUMemChartCID}}
<tr><td style="padding:10px 30px;">
  <img src="cid:{{.CPUMemChartCID}}" alt="Recent Status" style="max-width:100%;height:auto;" />
</td></tr>
{{end}}

<!-- Footer -->
<tr><td style="padding:15px 30px;background:#f8f8f8;border-top:1px solid #e0e0e0;text-align:center;">
  <p style="margin:0;font-size:11px;color:#999;">Generated by Firewall Monitor</p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`))
