package report

import "html/template"

// dailyTemplate is the HTML template for daily reports.
var dailyTemplate = template.Must(template.New("daily").Parse(`<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background:#f4f4f4;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;">

<!-- Header -->
<tr><td style="background:#1a73e8;padding:20px 30px;">
  <h1 style="margin:0;color:#ffffff;font-size:22px;">Firewall Monitor — Daily Report</h1>
  <p style="margin:5px 0 0;color:#c4dafb;font-size:13px;">{{.Date}} ({{.Timezone}})</p>
</td></tr>

<!-- Fleet Summary -->
<tr><td style="padding:20px 30px;">
  <h2 style="margin:0 0 10px;font-size:16px;color:#333;">Fleet Summary</h2>
  <table width="100%" cellpadding="6" cellspacing="0" style="border:1px solid #e0e0e0;border-radius:4px;font-size:13px;">
  <tr style="background:#f8f8f8;">
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Total Devices</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.TotalDevices}}</td>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Online</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;color:#34a853;">{{.OnlineDevices}}</td>
  </tr>
  <tr>
    <td><strong>Offline</strong></td>
    <td style="color:#ea4335;">{{.OfflineDevices}}</td>
    <td><strong>Alerts ({{.Hours}}h)</strong></td>
    <td>{{.TotalAlerts}}</td>
  </tr>
  </table>
</td></tr>

<!-- Per-Device Sections -->
{{range .Devices}}
<tr><td style="padding:10px 30px 0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e0e0e0;border-radius:4px;margin-bottom:15px;">
  <tr><td style="background:#f8f8f8;padding:10px 15px;border-bottom:1px solid #e0e0e0;">
    <span style="font-size:14px;font-weight:bold;color:#333;">{{.DeviceName}}</span>
    {{if eq .Status "online"}}
      <span style="display:inline-block;background:#34a853;color:#fff;padding:2px 8px;border-radius:3px;font-size:11px;margin-left:8px;">ONLINE</span>
    {{else}}
      <span style="display:inline-block;background:#ea4335;color:#fff;padding:2px 8px;border-radius:3px;font-size:11px;margin-left:8px;">OFFLINE</span>
    {{end}}
    <span style="float:right;color:#666;font-size:12px;">{{.IPAddress}}</span>
  </td></tr>

  <!-- Status Summary -->
  <tr><td style="padding:10px 15px;">
    <table width="100%" cellpadding="4" cellspacing="0" style="font-size:12px;">
    <tr>
      <td><strong>CPU avg:</strong> {{printf "%.1f" .CPUAvg}}%</td>
      <td><strong>CPU max:</strong> {{printf "%.1f" .CPUMax}}%</td>
      <td><strong>Mem avg:</strong> {{printf "%.1f" .MemAvg}}%</td>
      <td><strong>Mem max:</strong> {{printf "%.1f" .MemMax}}%</td>
    </tr>
    <tr>
      <td><strong>Disk:</strong> {{printf "%.1f" .DiskUsage}}%</td>
      <td><strong>Sessions:</strong> {{.SessionCount}}</td>
      <td colspan="2"><strong>Alerts:</strong> {{.AlertCount}}</td>
    </tr>
    </table>
  </td></tr>

  <!-- Uptime Meter -->
  {{if .UptimeChartCID}}
  <tr><td style="padding:5px 15px;">
    <img src="cid:{{.UptimeChartCID}}" alt="Uptime" style="max-width:100%;height:auto;" />
  </td></tr>
  {{end}}

  <!-- CPU/Memory Chart -->
  {{if .CPUMemChartCID}}
  <tr><td style="padding:5px 15px;">
    <img src="cid:{{.CPUMemChartCID}}" alt="CPU/Memory" style="max-width:100%;height:auto;" />
  </td></tr>
  {{end}}

  <!-- Traffic Chart -->
  {{if .TrafficChartCID}}
  <tr><td style="padding:5px 15px;">
    <img src="cid:{{.TrafficChartCID}}" alt="Traffic" style="max-width:100%;height:auto;" />
  </td></tr>
  {{end}}

  <!-- Spikes -->
  {{if .Spikes}}
  <tr><td style="padding:5px 15px;">
    <p style="color:#ea4335;font-size:12px;margin:5px 0;"><strong>Traffic Spikes Detected:</strong></p>
    <ul style="margin:0;padding-left:20px;font-size:12px;">
    {{range .Spikes}}
      <li>{{.Interface}}: {{printf "%.0f" .Value}} bytes at {{.Timestamp.Format "15:04"}} (mean: {{printf "%.0f" .Mean}}, σ: {{printf "%.0f" .StdDev}})</li>
    {{end}}
    </ul>
  </td></tr>
  {{end}}

  </table>
</td></tr>
{{end}}

<!-- Alert Trend -->
{{if .AlertTrendCID}}
<tr><td style="padding:10px 30px;">
  <h2 style="margin:0 0 10px;font-size:16px;color:#333;">Alert Trend</h2>
  <img src="cid:{{.AlertTrendCID}}" alt="Alert Trend" style="max-width:100%;height:auto;" />
</td></tr>
{{end}}

<!-- Footer -->
<tr><td style="padding:15px 30px;background:#f8f8f8;border-top:1px solid #e0e0e0;text-align:center;">
  <p style="margin:0;font-size:11px;color:#999;">Generated by Firewall Monitor</p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`))

// criticalAlertTemplate is the HTML template for critical alert emails.
var criticalAlertTemplate = template.Must(template.New("critical").Parse(`<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background:#f4f4f4;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;">

<!-- Header -->
<tr><td style="background:#ea4335;padding:20px 30px;">
  <h1 style="margin:0;color:#ffffff;font-size:22px;">⚠ Critical Alert</h1>
  <p style="margin:5px 0 0;color:#f8c4c0;font-size:13px;">{{.Timestamp}}</p>
</td></tr>

<!-- Alert Details -->
<tr><td style="padding:20px 30px;">
  <table width="100%" cellpadding="8" cellspacing="0" style="border:1px solid #e0e0e0;border-radius:4px;font-size:13px;">
  <tr style="background:#fce8e6;">
    <td style="border-bottom:1px solid #e0e0e0;width:120px;"><strong>Alert Type</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.AlertType}}</td>
  </tr>
  <tr>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Device</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.DeviceName}} ({{.DeviceIP}})</td>
  </tr>
  <tr>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Message</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.Message}}</td>
  </tr>
  {{if .MetricName}}
  <tr>
    <td style="border-bottom:1px solid #e0e0e0;"><strong>Metric</strong></td>
    <td style="border-bottom:1px solid #e0e0e0;">{{.MetricName}}: {{printf "%.2f" .CurrentValue}} (threshold: {{printf "%.2f" .Threshold}})</td>
  </tr>
  {{end}}
  <tr>
    <td><strong>Status</strong></td>
    <td>{{.DeviceStatus}}</td>
  </tr>
  </table>
</td></tr>

<!-- CPU/Mem Chart if available -->
{{if .CPUMemChartCID}}
<tr><td style="padding:10px 30px;">
  <img src="cid:{{.CPUMemChartCID}}" alt="Recent Status" style="max-width:100%;height:auto;" />
</td></tr>
{{end}}

<!-- Footer -->
<tr><td style="padding:15px 30px;background:#f8f8f8;border-top:1px solid #e0e0e0;text-align:center;">
  <p style="margin:0;font-size:11px;color:#999;">Generated by Firewall Monitor</p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`))
